name: Remote Push

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.10
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.10
      - name: Generate
        run: |
          javac CommitGenerator.java
          java CommitGenerator
      - name: Update Repo
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: gen
          destination-github-username: 'SnoopyCodeX'
          destination-repository-name: 'Auto-Commit-Generator'
          target-directory: gen
          user-email: extremeclasherph@gmail.com
          commit-message: Update Changes
          target-branch: master
